# Generated by Django 3.1.7 on 2021-03-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='date_of_birth',
        ),
    ]
