# Generated by Django 3.1.7 on 2021-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0002_remove_accountholder_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='date_of_birth',
            field=models.DateField(default=1980),
            preserve_default=False,
        ),
    ]
